services:
  # kontener: data, uruchamia się jako pierwszy, kończy pracę i wychodzi
  data:
    build: ./data
    volumes:
      - ./data/videos:/data/videos:ro
      - ./data/annotations:/data/annotations:ro
      - frames_data:/data/frames
      - db_data:/data/db
    restart: on-failure

  engine:
    build: ./engine
    volumes:
      - ./data/annotations:/data/annotations:ro
      - ./data/annotations_traffic:/data/annotations_traffic:ro
      - ./data/annotations_vehicle:/data/annotations_vehicle:ro
      - frames_data:/data/frames
      - db_data:/data/db
      - ./output_videos:/app/output_videos
    restart: on-failure # na razie tak, potem unless-stopped
    environment:
      - EXPECTED_MODEL_HASH=f59b3d833e2ff32e194b5bb8e08d211dc7c5bdf144b90d2c8412c47ccfc83b36

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

volumes:
  db_data: # shared volume: SQLite
  frames_data: # shared volume: wyekstrahowane klatki
